import ITEMS from './ITEMS.js';
import CONTAINERS from './CONTAINERS.js';
import ACTIONS from './ACTIONS.js';

const CRAFT = {
	CAMPFIRE: {
		INGREDIENTS: [ITEMS.FIREWOOD, ITEMS.AXE, ITEMS.ROCK],
		CONTAINER: CONTAINERS.CAMPFIRE
	},
	WASH_HANDS: {
		INGREDIENTS: [ITEMS.BOTTLE, ITEMS.WATER],
		ACTION: ACTIONS.WASH_HANDS
	}
};

export default CRAFT;
