const ITEMS = {
	ASH: 'ASH',
	AXE: 'AXE',
	BOTTLE: 'BOTTLE',
	FIRE: 'FIRE',
	FIREWOOD: 'FIREWOOD',
	LETTER_BLANK: 'LETTER_BLANK',
	LETTER_RECEIVED: 'LETTER_RECEIVED',
	MEAT_COOKED: 'MEAT_COOKED',
	MEAT_RAW: 'MEAT_RAW',
	RAG: 'RAG',
	ROCK: 'ROCK',
	SHIRT: 'SHIRT',
	SHOVEL: 'SHOVEL',
	WATER: 'WATER'
};

export default ITEMS;
